# Python'a Giriş

In [1]:
import numpy as np
import pandas as pd

## Veri Tipleri ve Değişkenler  

### Tamsayılar | Integers

*Tamsayılar, kesikli değerler olarak bilinen, virgüllü değerler almayan veri tipleridir. Bir sepetteki elma sayısı tam sayılara örnek olabilir.*

In [2]:
a = 10
type(a)   

int

In [3]:
a*a

100

*Bellek içerisinde a = 10 nesnesini temsil etmek için gereken bit sayısı;*

In [4]:
a.bit_length()

4

In [5]:
a = 11.0
type(a)

float

**Karmaşık Sayılar** hem sayısal bir ifadenin hem de string bir ifadenin aynı eşitlikte yer alması anlamına gelmektedir. 

In [6]:
x=3+1j
type(x)

complex

In [7]:
a*x

(33+11j)

### Ondalıklı Sayılar | Floats

*Ondalıklı sayılar, sürekli değerler olarak bilinen, virgülden sonra değerler alabilen veri tipleridir. Bir bebeğin kilosu ondalıklı sayılara örnek olabilir.*

In [8]:
type(a)

float

In [9]:
b = a*100
b

1100.0

In [10]:
type(b)

float

*Bir tamsayı ile ondalıklı sayının çarpımı ondalıklı sayıdır :)*

In [11]:
c = 9/4
type(c)

float

In [12]:
c = 9//4
c

2

In [13]:
type(c)

int

**//** şeklinde bölme işlemi ile sonucu tamsayı değerine yuvarlamak mümkündür.

### Karakter Dizileri | Strings

*Tek tırnak veya üç tırnak ifadelerinin içerisine yazılan sayısal veya karakter tipindeki değerler string ifadelere dönüşmektedir.*

In [14]:
a = "bu 1. karakter dizisidir";a

'bu 1. karakter dizisidir'

In [15]:
type(a)

str

In [16]:
b = """
bu çok satırlı bir
karakter dizisidir.
"""
b

'\nbu çok satırlı bir\nkarakter dizisidir.\n'

*Yukarıda, üç tırnağın içerisine yazılan çok satırlı olarak saklanan veriler, \n yeni satır karakteri ile birlikte saklanır. Bu karakter dizisini çok satırlı olarak yazdırmak için print() fonksiyonu kullanılmaktadır.*

In [17]:
print(b)


bu çok satırlı bir
karakter dizisidir.



In [18]:
c = "3'üncü string ifadesi"

In [19]:
len(c)

21

*Length (len) fonksiyonu bir karakter dizisinin veya bir serinin uzunluğunu hesaplamaktadır. Harf, rakam, boşluk, noktalama işaretleri gibi tüm karakterleri saydırmaktadır.*

In [20]:
c = "3'üncü string         ifadesi"

In [21]:
len(c)

29

**Bir serinin i'inci elemanını yazdırmak;**

In [22]:
d = "Bir karakter serisinin içerisinde yer alan değerleri bulmak"
d

'Bir karakter serisinin içerisinde yer alan değerleri bulmak'

In [23]:
d[0]

'B'

In [24]:
d[0:19]

'Bir karakter serisi'

In [25]:
d[-1]

'k'

In [26]:
d[-6:]

'bulmak'

In [27]:
d[:-7]

'Bir karakter serisinin içerisinde yer alan değerleri'

**Bir serinin başka karakterler ile birleştirilmesi**

In [28]:
a = "Python eğitim serisi-"

In [29]:
len(a)

21

In [30]:
a[16] = "1"

TypeError: 'str' object does not support item assignment

Karakter serilerine atama yapmak için iki karakter serisi "+" işareti ile birbirlerine bağlanmalıdır.

In [31]:
a = a+"1"

In [32]:
a

'Python eğitim serisi-1'

**String Metotları;**

In [33]:
a.upper()

'PYTHON EĞITIM SERISI-1'

In [34]:
a.lower()

'python eğitim serisi-1'

In [35]:
a.replace("P", "f") + " :)"

'fython eğitim serisi-1 :)'

## Veri Yapıları 

- Listeler (Lists)
- Demetler (Tuples)
- Sözlükler (Dictionaries) 
- Setler (Sets) 

### Listeler | Lists

*Listeler, harf, rakam, boşluk, noktalama işaretleri, liste, tuple gibi bir çok farklı tipteki veriyi içerebilen veri yapılarından bir tanesidir.*

In [36]:
liste=["python ",4,"text",None,True,"book"];liste

['python ', 4, 'text', None, True, 'book']

String ifadelerde her bir harf veya sayı değerinin bir sıralaması olduğu gibi, listeler de içerisinde aynı sıralamaya göre değerleri içermektedir.

In [37]:
liste[0]

'python '

In [38]:
liste[0:3]

['python ', 4, 'text']

*Yukarıda belirttiğimiz üzere liste veri yapıları içlerine farklı listeler de alabilmektedir;*

In [39]:
liste_alt = [100, 101, 102]

In [40]:
all_liste = [liste, liste_alt]

*liste ve liste_alt nesneleri birleştirilip yeni bir nesne oluşturduğunda yeni liste 2 elemanlı bir liste boyutunda olacaktır*

In [41]:
len(all_liste)

2

In [42]:
all_liste[0]

['python ', 4, 'text', None, True, 'book']

In [43]:
all_liste[1]

[100, 101, 102]

# <font color='#F39C12'>**Soru 1**</font> 

Aşağıdaki liste kaç elemanlıdır?


In [44]:
liste = [22, 33, ['python ', 4, 'text', None, True, 'book']]

In [47]:
len(liste)

3

**Listelerde eleman işlemleri**

In [48]:
liste = ["R", "Python", "Hadoop"]

*Eleman ekleme* | append()

In [49]:
liste.append("Spark")

In [50]:
liste

['R', 'Python', 'Hadoop', 'Spark']

*Eleman silme* | remove(), del, pop()

In [51]:
liste.remove("Hadoop")

In [52]:
liste

['R', 'Python', 'Spark']

In [53]:
del liste[0]

In [54]:
liste

['Python', 'Spark']

In [55]:
liste.pop(1)

'Spark'

**Extend() ve Append()** fonksiyonları;

In [56]:
t = [1,2,3]

*Yeni eklenecek bir seriyi, listenin birer elemanı gibi listenin içine dahil etmek*

In [57]:
t.extend([101, 102, 103])

In [58]:
t

[1, 2, 3, 101, 102, 103]

*Yeni eklenecek bir seriyi, listenin içerisine yeni bir liste olarak dahil etmek*

In [59]:
t.append([101, 102, 103])

In [60]:
t

[1, 2, 3, 101, 102, 103, [101, 102, 103]]

**Liste elemanlarını değiştirmek**

In [61]:
t[2] = 999
t

[1, 2, 999, 101, 102, 103, [101, 102, 103]]

**Listeyi Sıralamak** | sort()

Bir listenin içerisinde başka listeler olduğu durumda sort() işlemini yapmak için tek elemanlı bir listenin lokasyonunu belirtmek gerekmektedir. Aksi takdirde aşağıdaki hata ile karşılaşılmaktadır.

In [62]:
t.sort()

TypeError: '<' not supported between instances of 'list' and 'int'

Listenin son elemanı olan [101, 102, 103] listesini kaldırıp sıralama işlemi aşağıdaki gibidir;

In [63]:
t[-1].sort()

In [64]:
t

[1, 2, 101, 102, 103, 999, [101, 102, 103]]

Karakter serilerini sıralamak;

In [65]:
karakter_listesi = ["yüz", "Mavi", "mutlu", "gülen"]

In [66]:
karakter_listesi.sort()
karakter_listesi

['Mavi', 'gülen', 'mutlu', 'yüz']

Karakter serilerini **reverse()** fonksiyonu ile çevirmek

In [67]:
karakter_listesi.reverse();karakter_listesi

['yüz', 'mutlu', 'gülen', 'Mavi']

Karakter serilerine **insert()** fonksiyonu ile yeni değerler atamak;

In [68]:
karakter_listesi.insert(1, "999");karakter_listesi

['yüz', '999', 'mutlu', 'gülen', 'Mavi']

Karakter serilerini **clear()** fonksiyonu ile temizlemek;

In [69]:
karakter_listesi.clear(); karakter_listesi

[]

### Demetler | Tuples

Tuple veri tipi, listeler gibi içerisinde harf, rakam, boşluk, noktalama işaretleri, tuple tipi verileri barındırabilir. Listelerden en önemli farkı, listelerin içerisinden veri silme işlemi yapılabiliyorken, tuple tipi verilere ekleme, çıkarma, değiştirme işlemleri uygulanamamasıdır.

In [70]:
"Python","Java","Ruby","JavaScript"

('Python', 'Java', 'Ruby', 'JavaScript')

In [71]:
t = 1,2

In [72]:
type(t)

tuple

In [73]:
t = "Python","Java","Ruby","JavaScript"

In [74]:
t[1]

'Java'

In [75]:
a = "Python eğitim serisi-1"

In [76]:
tuple(a)

('P',
 'y',
 't',
 'h',
 'o',
 'n',
 ' ',
 'e',
 'ğ',
 'i',
 't',
 'i',
 'm',
 ' ',
 's',
 'e',
 'r',
 'i',
 's',
 'i',
 '-',
 '1')

In [77]:
a[0:6]

'Python'

**Tuple veri işlemleri**

**count()** fonksiyonu ile tuple'ın içerisindeki eleman sayılarına ulaşmak;

In [78]:
a.count("e")

2

**index()** fonksiyonu ile girilen değerin lokasyonuna ulaşmak;

In [79]:
a.index("e")

7

**in** fonksiyonu ile bir tuple'ın içerisinde değer olup olmadığını incelemek;

In [80]:
"python" in a

False

In [81]:
"P" in a

True

### Sözlükler | Dictionaries

- Key (anahtar) ve Value (değer) mantığı ile iki kısımdan oluşmaktadır.
- Key kısmı sadece string tipi veriler içerebilirken, value kısmı farklı veri tiplerinde değer alabilir.


In [82]:
yapay_zeka = {}

In [83]:
yapay_zeka["Machine Learning"] = 95

In [84]:
yapay_zeka

{'Machine Learning': 95}

In [85]:
yapay_zeka["Statistical Learning"] = 80
yapay_zeka["Deep Learning"] = 90

In [86]:
yapay_zeka

{'Machine Learning': 95, 'Statistical Learning': 80, 'Deep Learning': 90}

In [87]:
yapay_zeka[1]

KeyError: 1

*Sözlüklerde değerleri seçme işlemi liste tipi verilere göre farklılıklar göstermektedir. Key-value mantığı ile kurulmuş yapılar olduğu için bir değeri seçmek için ilgili Key veya Value değerini aratmak gerekir;*

In [88]:
yapay_zeka.keys()

dict_keys(['Machine Learning', 'Statistical Learning', 'Deep Learning'])

In [89]:
yapay_zeka.values()

dict_values([95, 80, 90])

In [90]:
yapay_zeka.items()

dict_items([('Machine Learning', 95), ('Statistical Learning', 80), ('Deep Learning', 90)])

**update** fonksiyonu ile sözlüğe eleman ekleme;

In [91]:
yapay_zeka.update({"Matematical Statistics":10, "Robots": 60});yapay_zeka

{'Machine Learning': 95,
 'Statistical Learning': 80,
 'Deep Learning': 90,
 'Matematical Statistics': 10,
 'Robots': 60}

In [92]:
yapay_zeka.update({"Programming Languages": ["R", "Python", "Scala"]})

In [93]:
yapay_zeka

{'Machine Learning': 95,
 'Statistical Learning': 80,
 'Deep Learning': 90,
 'Matematical Statistics': 10,
 'Robots': 60,
 'Programming Languages': ['R', 'Python', 'Scala']}

In [94]:
yapay_zeka["Robots"]

60

In [95]:
yapay_zeka.get("Machine Learning")

95

In [96]:
yapay_zeka.get('Programming Languages')[1]

'Python'

### Setler | Sets

*Setler bir serinin tekil elemanlarını içerir*

In [97]:
a = {1,1,1,2,5,5,1,3,3,3,2}

In [98]:
a

{1, 2, 3, 5}

In [99]:
type(a)

set

In [100]:
b = {4,4,4,3,2,2,2,1,3,4,99}

In [101]:
b

{1, 2, 3, 4, 99}

In [102]:
a | b # birleşim/union

{1, 2, 3, 4, 5, 99}

In [103]:
a & b # kesişim/intersection

{1, 2, 3}

In [104]:
a-b # difference

{5}

In [105]:
managers={"tom","sue"}
engineers={"bob","sue","ann","vic"}

In [106]:
"bob" in engineers

True

In [107]:
engineers&managers

{'sue'}

## Temel İfadeler 

**Aritmetik İfadeler**

**(+)** >>> Toplama

**(-)** >>> Çıkarma

**(*)** >>> Çarpma

**(/)** >>> Bölme

**(**)** >>> Kuvvet alma

**(%)** >>> Mod alma

**(//)** >>> Taban bölme

**Mantıksal İşlemler**

**AND** >>> ve 

**OR** >>> veya

**NOT** >>> değil

**Değer Atama İşlemleri**
    
**=** >>> Değer ata

**+=** >>> Topla ve değer ata

**-=** >>> Çıkar ve değer ata

**/=** >>> Böl ve değer ata

**//=** >>> Tabanını al ve değer ata

****=** >>> Kuvvetini al ve değer ata

**İlişkisel Operatörler**

**>** >>> Büyüktür

**<** >>> Küçüktür

**==** >>> Eşit midir?

**!=** >>> Eşit değil midir?

**>=** >>> Büyük eşit

**<=** >>> Küçük eşit

## Kontrol Yapıları  

**TRUE-FALSE Sorgulamaları**

In [108]:
language = "python"

**==** *ifadesi ile karakter, liste, sözlük gibi veri yapılarının içerisinde yer alan değerleri sorgulama işlemi yapılmaktadır. Sonucun doğruluğuna göre True, False sonucu dönmektedir.*

In [109]:
language == "python"

True

In [110]:
language == "Python"

False

In [111]:
language == "scala"

False

**if-elif-else** Kontrol Yapıları

*Bir kuyrukta bekleme süresini ele alalım;*

In [112]:
ortalama_zaman = 5000
gecen_zaman = 5500

In [113]:
if ortalama_zaman < gecen_zaman:
    print("Bekleme süresi ortalamayı aşmıştır.")

Bekleme süresi ortalamayı aşmıştır.


In [114]:
ortalama_zaman < gecen_zaman

True

In [115]:
if ortalama_zaman < gecen_zaman:
    print("Bekleme süresi ortalamayı aşmıştır.")
    print("Fazladan bekleme süresi", gecen_zaman - ortalama_zaman, "dakika")

Bekleme süresi ortalamayı aşmıştır.
Fazladan bekleme süresi 500 dakika


In [116]:
if ortalama_zaman > gecen_zaman:
    print("Bekleme süresi ortalamayı aşmamıştır.")

In [117]:
if ortalama_zaman < gecen_zaman:
    print("Bekleme süresi ortalamayı aşmıştır.")
    print("Fazladan bekleme süresi", gecen_zaman - ortalama_zaman, "dakika")
else:
    print("Bekleme süresi ortalamayı aşmamıştır.")

Bekleme süresi ortalamayı aşmıştır.
Fazladan bekleme süresi 500 dakika


In [118]:
ortalama_zaman = 5000
gecen_zaman = 4500

if ortalama_zaman < gecen_zaman:
    print("Bekleme süresi ortalamayı aşmıştır.")
    print("Fazladan bekleme süresi", gecen_zaman - ortalama_zaman, "dakika")
else:
    print("Bekleme süresi ortalamayı aşmamıştır.")

Bekleme süresi ortalamayı aşmamıştır.


In [119]:
ortalama_zaman = 5000
gecen_zaman = 5000

if ortalama_zaman < gecen_zaman:
    print("Bekleme süresi ortalama bekleme süresini aşmıştır.")
    print("Fazladan bekleme süresi", gecen_zaman - ortalama_zaman, "dakika")
elif ortalama_zaman == gecen_zaman:
    print("Bekleme süresi ortalama bekleme süresine eşittir.")
else:
    print("Bekleme süresi ortalama bekleme süresini aşmamıştır.")

Bekleme süresi ortalama bekleme süresine eşittir.


In [120]:
ortalama_zaman = 5000
gecen_zaman = input("Lutfen bekleme surenizi giriniz: ")

if ortalama_zaman <= int(gecen_zaman):
    print("\nTebrikler promosyon kazandınız!")
else:
    print("\nAlışverişe başlayabilirsiniz!")


Lutfen bekleme surenizi giriniz: 10

Alışverişe başlayabilirsiniz!


## Döngüler

### For Döngüleri | For loops

Bir liste veya sözlük tipindeki verilerin her bir elemanını gezmek ve bir işlem uygulayabilmek için listeyi bir döngünün içerisine sokarak, döngünün tek tek her bir elemanı gezmesi sağlanabilir.

In [3]:
sinav_notlari = [80, 64, 78, 92, 55]

In [4]:
sinav_notlari[0]

80

In [5]:
for i in sinav_notlari:
    print(i)

80
64
78
92
55


In [6]:
for i in range(len(sinav_notlari)):
    print(i)

0
1
2
3
4


# <font color='#F39C12'>**Soru 2**</font> 

Lütfen for döngüsünü kullanarak bir listenin kaçıncı elemanının hangi eleman olduğunu yazdırınız.

Örnek çıktı: **Listenin 1. elemanı 80'dir.**

DATA OKUTMA - NAMESPACE LER MODÜLLER 

In [8]:
for i in range(len(sinav_notlari)):
    print("Listenin " , i+1 , ". elemani" , sinav_notlari[i] , "'dir")


Listenin  1 . elemani 80 'dir
Listenin  2 . elemani 64 'dir
Listenin  3 . elemani 78 'dir
Listenin  4 . elemani 92 'dir
Listenin  5 . elemani 55 'dir


In [12]:
for i,j in enumerate(sinav_notlari):
    print("Listenin " , i+1 , ". elemani" , j, "'dir")

Listenin  1 . elemani 80 'dir
Listenin  2 . elemani 64 'dir
Listenin  3 . elemani 78 'dir
Listenin  4 . elemani 92 'dir
Listenin  5 . elemani 55 'dir


In [126]:
d = {"a":1,"b":2,"c":3}
for i in d:
    print(i) # 9-10.30 9.30

a
b
c


In [127]:
d = {"a":1,"b":2,"c":3}
for i,j in d.items():
    print(i,j)

a 1
b 2
c 3


Maaşlara %20 zam yapmak;

In [128]:
maaslar = {"james" : 5000, "marry" : 5500, "harry" : 4700}
maaslar

{'james': 5000, 'marry': 5500, 'harry': 4700}

In [129]:
for x,y in maaslar.items():
    maaslar[x]=y+y*0.2

In [130]:
maaslar

{'james': 6000.0, 'marry': 6600.0, 'harry': 5640.0}

### While Döngüleri | While Loops

While döngüleri, bir koşul sağlanana kadar çalışan döngülerdir.

In [131]:
a = 0
while a<5:
    b = a**3
    print(a, ">>>", b)
    a +=1

0 >>> 0
1 >>> 1
2 >>> 8
3 >>> 27
4 >>> 64


In [132]:
import random
a = 0; counter = 0
while a!=3:
    a = random.randint(0,10)
    counter += 1
    
print("tekrar sayisi",counter)
print("yaratilan son sayi", a)

tekrar sayisi 11
yaratilan son sayi 3


**break, continue** ifadeleri

**break :** döngüler içerisinde belirli bir şartın sağlandığında döngüyü bitirir

**continue :** döngüler içerisinde belirli bir şartın sağlandığında bu şartı sağlayan eleman görmezden gelir 

In [133]:
maaslar = [8000, 6600, 7800, 9000, 7700]
maaslar.sort();maaslar

[6600, 7700, 7800, 8000, 9000]

In [134]:
for i in maaslar:
    if i >= 8000:
        print("islem kesildi")
        break
    print(i)

6600
7700
7800
islem kesildi


In [135]:
for i in maaslar:
    if i == 7800:
        print("islem atlandı")
        continue
    print(i)

6600
7700
islem atlandı
8000
9000


In [136]:
sayi = 0
while sayi<10:
    sayi += 1
    if sayi == 2:
        continue
    print(sayi)

1
3
4
5
6
7
8
9
10


## Fonksiyonlar

Basit ve/veya karmaşık işlemleri bir araya getirerek, farklı amaçlara uygun bir şekilde esnek olarak çalışabilen yöntemlerdir. print() fonksiyonu bir nesne içerisindeki elemanları ekrana yazdıran bir fonksiyondur. Bu şekilde farklı amaçlara hizmet eden fonksiyonlar üretmek mümkündür.

In [137]:
def kok_al(x):
    print(int(np.sqrt(x)))

kok_al(4) 

2


In [138]:
kareler = [1, 4, 9, 16, 25, 36, 49]
for i in kareler:
    kok_al(i)

1
2
3
4
5
6
7


# <font color='#F39C12'>**Soru 3**</font> 

Lütfen for döngüsünü ve if kontrolü kullanarak, **kareler** listenin içerisindeki 3. elemanı işleme dahil etmeden kök alma (kok_al) fonksiyonunu uygulayınız.

Örnek çıktı: **1 2 3 5 6 7**

In [141]:
for i in range(len(kareler)):
    if i == 3:
        continue
    kok_al(kareler[i])
    i += 1

1
2
3
5
6
7


# <font color='#F39C12'>**Soru 4**</font> 

Vücut Kitle Endeksi (BMI) hesaplayan ve girilen sayılara göre kategorisini belirleyen bir fonksiyon yazınız.

* BMI = ağırlık(kg) * boy(m)^2

* Underweight	< 18.5

* Healthy weight	< 26

* At risk of overweight	< 32

* Overweight	> 32


Örnek çıktı: **Healthy weight - BMI = 24.221453287197235**

In [145]:
def BMI_calc(boy, kilo):
    BMI = kilo / boy**2
    if BMI < 18.5:
        print("Underweight - ", "BMI =", BMI)
    elif BMI < 26:
        print("Healthy weight -", "BMI =", BMI)
    elif BMI < 32:
        print("At risk of overweight -", "BMI = ", BMI)
    else:
        print("Overweight-", "BMI = ", BMI)

BMI_calc(boy = 1.75, kilo = 70)

Healthy weight - BMI = 22.857142857142858


*Bu bölüme kadar fonksiyonların çıktısını ekrana yazdırma işlemleri yapmıştık. Ancak bir fonksiyonun çıktısı başka bir fonksiyonun girdisi olabilir. Bunun için **return** fonksiyonu kullanılmalıdır.*

In [146]:
def kok_al(x):
    print(np.sqrt(x))

kok_al(4) 

2.0


In [147]:
kok_al(4)*2

2.0


TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

In [148]:
def kok_al(x):
    return np.sqrt(x)

kok_al(4)*2 

4.0

**Lambda Fonksiyonları**

In [149]:
def kare_alma(x):
    return x**2

In [150]:
kare_alma(4)

16

In [151]:
kare_alma_lambda = lambda x: x**2

In [152]:
kare_alma_lambda(4)

16

In [153]:
topla = lambda a, b, c : print(a + b + c)
 
topla(3,4,5)

12


In [154]:
cevirme = lambda string: string[::-1]
cevirme("Python training-1")

'1-gniniart nohtyP'

# Veri Okuma İşlemleri

**open() fonksiyonu ile veri okuma işlemi**

In [130]:
lines=open("sales.csv")
lines


<_io.TextIOWrapper name='sales.csv' mode='r' encoding='cp1254'>

In [131]:
lines = lines.readlines();lines

['customerid,name,gender,city,phone,item,item quantity,payment\n',
 '2010101,Cengiz,e,istanbul,2122851784,buzdolabÄ±,1,500$\n',
 '2010105,merve,k,bursa,2242851784,Ã§amaÅŸÄ±r makinesi,2,100Â£\n',
 '2017104,kemal,e,ankara,3122851784,bulaÅŸÄ±k makinesi,3,300â‚¬\n',
 '2012404,canan,k,izmir,2322851784,dondurucu,1,100$\n',
 '2013504,mert,e,ankara,3129998899,fÄ±rÄ±n,2,50Â£\n',
 '2008504,lale,k,istanbul,2122851784,televizyon,4,250â‚¬\n',
 '2011107,burak,e,izmir,2322851785,buzdolabÄ±,2,300Â£\n',
 '2015403,hilal,k,bursa,2242851784,fÄ±rÄ±n,4,250$\n',
 '2013343,tamer,e,istanbul,2122851784,Ã§amaÅŸÄ±r makinesi,3,400â‚¬\n']

In [133]:
lines[1].split(",")

['2010101',
 'Cengiz',
 'e',
 'istanbul',
 '2122851784',
 'buzdolabÄ±',
 '1',
 '500$\n']

In [142]:
for satir in lines:
    print(satir)

customerid,name,gender,city,phone,item,item quantity,payment

2010101,Cengiz,e,istanbul,2122851784,buzdolabÄ±,1,500$

2010105,merve,k,bursa,2242851784,Ã§amaÅŸÄ±r makinesi,2,100Â£

2017104,kemal,e,ankara,3122851784,bulaÅŸÄ±k makinesi,3,300â‚¬

2012404,canan,k,izmir,2322851784,dondurucu,1,100$

2013504,mert,e,ankara,3129998899,fÄ±rÄ±n,2,50Â£

2008504,lale,k,istanbul,2122851784,televizyon,4,250â‚¬

2011107,burak,e,izmir,2322851785,buzdolabÄ±,2,300Â£

2015403,hilal,k,bursa,2242851784,fÄ±rÄ±n,4,250$

2013343,tamer,e,istanbul,2122851784,Ã§amaÅŸÄ±r makinesi,3,400â‚¬



In [140]:
pd.read_csv("sales.csv")

customerid    name gender      city       phone              item  \
0     2010101  Cengiz      e  istanbul  2122851784         buzdolabı   
1     2010105   merve      k     bursa  2242851784  çamaşır makinesi   
2     2017104   kemal      e    ankara  3122851784  bulaşık makinesi   
3     2012404   canan      k     izmir  2322851784         dondurucu   
4     2013504    mert      e    ankara  3129998899             fırın   
5     2008504    lale      k  istanbul  2122851784        televizyon   
6     2011107   burak      e     izmir  2322851785         buzdolabı   
7     2015403   hilal      k     bursa  2242851784             fırın   
8     2013343   tamer      e  istanbul  2122851784  çamaşır makinesi   

   item quantity payment  
0              1    500$  
1              2    100£  
2              3    300€  
3              1    100$  
4              2     50£  
5              4    250€  
6              2    300£  
7              4    250$  
8              3    400€

# Numpy 

- Numerical Python ifadesinin kısaltılmışıdır.
- Seriler, çok boyutlu seriler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
- Listelere benzerdir, verimli veri saklama konusunda listelere göre daha az maliyetlidir.

In [155]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [156]:
a = np.array([1,2,3,4])

In [157]:
type(a)

numpy.ndarray

*Veriye farklı tipte veri eklendiği numpy tüm değerleri o tipe dönüştürüp tek bir tip olarak veriyi saklamaktadır.*

In [158]:
np.array([1.618,2,3,4])

array([1.618, 2.   , 3.   , 4.   ])

In [159]:
[1.618,2,3,4]

[1.618, 2, 3, 4]

In [160]:
np.array([1.618,2,3,4], dtype = "float32")

array([1.618, 2.   , 3.   , 4.   ], dtype=float32)

In [161]:
np.array([1.618,2,3,4], dtype = "int")

array([1, 2, 3, 4])

**Array oluşturma işlemi**

**np.zeros()**

In [162]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**np.ones()**

In [163]:
np.ones((3,5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**np.full()** : *istenilen sayı değerini içeren 2 boyutlu matris oluşturma işlemi*

In [164]:
np.full((3,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

**np.arange()** : *0'dan 20'ye kadar 3'er 3'er artan seri oluşturma işlemi*

In [165]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

**np.random.normal()** : *2 ortalamalı 1 standart sapmalı 2 boyutlu veri türetme işlemi*

In [166]:
np.random.normal(2, 1, (2,2))

array([[1.98654761, 4.03944032],
       [4.01945507, 2.58644271]])

**np.random.randint()** : *istenilen aralıklarda 2 boyutlu veri türetme işlemi*

In [167]:
np.random.randint(0, 20, (2,2))

array([[ 8, 10],
       [10, 10]])

**numpy array'i keşfetme işlemi**

In [168]:
a = np.array([[1,2,3],[4,5,6]]);a

array([[1, 2, 3],
       [4, 5, 6]])

**size** : *Bir listenin kaç elemanlı olduğunu bulma işlemi* 

In [169]:
a.size

6

**shape** : *Bir listenin kaç satır ve sütunlu olduğunu bulma işlemi*

In [170]:
a.shape

(2, 3)

**ndim** : *Bir listenin kaç boyutlu olduğunu bulma işlemi*

In [171]:
a.ndim

2

**dtype** : *Bir listenin elemanlarının hangi tip veri içerdiğini bulma işlemi. Numpy arrayleri, serileri tek tipte verilere çevirerek bu şekilde sakladığından listelere göre çok daha hızlı işlem kapasitesine sahiptir.*

In [172]:
a.dtype

dtype('int32')

**astype()** : *Bir serinin elemanlarını farklı bir tipe çevirme işlemi*

In [173]:
a.astype("float32")

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

*Seriye yeni bir vectör ekleme işlemi*

**append()** : *Bir seriye istenilen satır veya sütun bazında veri ekleme işlemi*

In [174]:
a = np.append(a,[[44,55,66]],axis=0);a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [44, 55, 66]])

In [175]:
a = np.append(a, [[999], [999], [999]], axis = 1)

*np serilere çarpma işlemini uygulamak*

In [176]:
a*4

array([[   4,    8,   12, 3996],
       [  16,   20,   24, 3996],
       [ 176,  220,  264, 3996]])

*Serinin boyutlarını değiştirme işlemi*

**reshape()** : *Bir serinin elemanlarını farklı satır veya sütunlara çevirme işlemi*

In [177]:
a = np.arange(9);a 

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [178]:
a.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

*Seri birleştirme işlemi*

**concatenate()** : *Farklı serileri satır veya sütun bazında birleştirme işlemi*

In [179]:
np.array([[1,2,3], [11,22,33]])

array([[ 1,  2,  3],
       [11, 22, 33]])

In [180]:
a = np.array([[1,2,3], [11,22,33]])
b = np.array([[44,55,66], [77,88,99]])

In [181]:
np.concatenate([a,b])

array([[ 1,  2,  3],
       [11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [182]:
np.concatenate([a,b], axis = 1)

array([[ 1,  2,  3, 44, 55, 66],
       [11, 22, 33, 77, 88, 99]])

*Seri ayırma işlemi*

**split()** : *Tek boyutlu serileri istenilen uzunluklara bölme işlemi*

In [183]:
x = np.array([1,2,3,44,55,66,77,88,99])

In [184]:
np.split(x, [2, 5])

[array([1, 2]), array([ 3, 44, 55]), array([66, 77, 88, 99])]

In [185]:
a,b,c = np.split(x, [2, 5])

In [186]:
b

array([ 3, 44, 55])

**vsplit()** : *1'den çok boyutlu bir seriyi dikey olarak (rowwise) birden çok alt kümeye ayırma işlemi*

In [187]:
m = np.arange(15).reshape(3,5)

In [188]:
a, b = np.vsplit(m, [1])

In [189]:
a

array([[0, 1, 2, 3, 4]])

In [190]:
b

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**hsplit()** : *1'den çok boyutlu bir seriyi yatay olarak (colwise) birden çok alt kümeye ayırma işlemi*

In [191]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [192]:
np.hsplit(m, [3])[0]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [193]:
np.hsplit(m, [3])[1]

array([[ 3,  4],
       [ 8,  9],
       [13, 14]])

**sort()** : *Serileri sıralama işlemi*

In [194]:
m = np.random.randint(16, size=10)

In [195]:
m

array([ 3, 14,  7, 13,  1,  8,  4,  3,  8,  4])

In [196]:
np.sort(m) # inplace = False

array([ 1,  3,  3,  4,  4,  7,  8,  8, 13, 14])

In [197]:
m

array([ 3, 14,  7, 13,  1,  8,  4,  3,  8,  4])

In [198]:
m.sort() # inplace = True

In [199]:
m

array([ 1,  3,  3,  4,  4,  7,  8,  8, 13, 14])

*İki boyutlu serileri sıralama işlemi*

In [200]:
m = np.random.randint(20, size = (4,5))

In [201]:
np.sort(m, axis=1) # rowwise

array([[ 3,  4,  9, 17, 19],
       [ 2,  9,  9, 13, 18],
       [ 1,  1, 17, 17, 19],
       [ 1,  6, 11, 11, 15]])

In [202]:
np.sort(m, axis=0) # colwise

array([[ 1,  9, 11,  1,  3],
       [ 2, 11, 13,  1,  9],
       [ 6, 17, 17,  4, 15],
       [ 9, 19, 19, 18, 17]])

*Index elemanlarına erişme işlemi - 2D*

In [203]:
m = np.random.randint(20, size = (4,5))

In [204]:
m

array([[ 0,  7, 14,  9, 12],
       [18, 18,  1,  6,  3],
       [ 5, 12,  6,  1,  7],
       [18,  9,  2, 16, 16]])

*Köşeli parantez kullanarak değerlerin matris içerisindeki lokasyonlarına göre eleman bulma işlemi*

In [205]:
m[0,1]

7

In [206]:
m[:,1]

array([ 7, 18, 12,  9])

In [207]:
m[0,0] = 3.3

In [208]:
m

array([[ 3,  7, 14,  9, 12],
       [18, 18,  1,  6,  3],
       [ 5, 12,  6,  1,  7],
       [18,  9,  2, 16, 16]])

*Var olan bir array'e dışarıdan farklı tipteki bir ekleme yapıldığında varolan tipi bozmadığından 3.3 değerini 3 değerine yuvarladı*

**Köşeli parantez kullanarak veriden dilimler alma işlemi**

In [209]:
m = np.arange(10, 21)

In [210]:
m

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

*0'ıncı ve 2'inci sıradaki elemanlar arası değer seçme işlemi*

In [211]:
m[0:2]

array([10, 11])

*0'ıncı elemandan itibaren 1 eleman boşluk bırakarak değer seçme işlemi*

In [212]:
m[0::2] 

array([10, 12, 14, 16, 18, 20])

In [213]:
m[1::3] 

array([11, 14, 17, 20])

*İki boyutlu serilerde dilimler alma işlemi*

In [218]:
m = np.random.randint(10, size = (5,5))

In [223]:
m

array([[9, 7, 9, 9, 0],
       [7, 7, 2, 1, 7],
       [1, 0, 2, 1, 9],
       [7, 0, 4, 9, 2],
       [7, 2, 8, 0, 8]])

In [224]:
m[0,4]

0

*Tüm satır veya sütun seçme işlemlerinde **:** işareti kullanılırken, belirli bir lokasyon seçimi için **i:j** şeklinde seçim işlemi yapılmaktadır.*

In [225]:
m[0,:]

array([9, 7, 9, 9, 0])

In [231]:
m[0]

array([9, 7, 9, 9, 0])

In [229]:
m[0,3:5]

array([9, 0])

In [230]:
m[:,1]

array([7, 7, 0, 0, 2])

In [232]:
m[0:2, 0:3]

array([[9, 7, 9],
       [7, 7, 2]])

**copy()** : *Seriye değer atama işlemleri sonrasında eski serinin bozulmasını engelleme işlemi* 

In [238]:
m

array([[9, 7, 9, 9, 0],
       [7, 7, 2, 1, 7],
       [1, 0, 2, 1, 9],
       [7, 0, 4, 9, 2],
       [7, 2, 8, 0, 8]])

In [236]:
m_alt = m[0:3,0:3]

In [239]:
m_alt

array([[9, 7, 9],
       [7, 7, 2],
       [1, 0, 2]])

In [241]:
m_alt[0,0] = 111
m_alt[0,1] = 222
m_alt

array([[111, 222,   9],
       [  7,   7,   2],
       [  1,   0,   2]])

In [242]:
m

array([[111, 222,   9,   9,   0],
       [  7,   7,   2,   1,   7],
       [  1,   0,   2,   1,   9],
       [  7,   0,   4,   9,   2],
       [  7,   2,   8,   0,   8]])

*Yapılan değişiklikler ana seri üzerinde de uygulanmış oldu. Bu durumu engellemek, ana array'in sabit olarak kalmasını sağlamak için copy() fonksiyonundan yararlanılır*

In [245]:
t = np.random.randint(20, size = (4,5))
t

array([[ 1, 10, 11, 16, 15],
       [ 9,  4,  3,  0, 18],
       [15,  0,  5, 12,  9],
       [15, 15,  8,  8,  7]])

In [250]:
t_alt = t[0:3, 0:3].copy()
t_alt

array([[ 1, 10, 11],
       [ 9,  4,  3],
       [15,  0,  5]])

In [252]:
t_alt[0,0] = 111
t_alt

array([[111,  10,  11],
       [  9,   4,   3],
       [ 15,   0,   5]])

In [253]:
t

array([[ 1, 10, 11, 16, 15],
       [ 9,  4,  3,  0, 18],
       [15,  0,  5, 12,  9],
       [15, 15,  8,  8,  7]])

*Fancy index yöntemi ile serinin içerisinden spesifik olarak gözlem seçme işlemi - 1D*

In [270]:
s = np.arange(0, 40, 4)

In [271]:
fancy = [0, 4, 7]

In [272]:
s[fancy]

array([ 0, 16, 28])

*Fancy index yöntemi ile serinin içerisinden spesifik olarak gözlem seçme işlemi - 2D*

In [283]:
s = np.arange(20).reshape(4,5)
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [298]:
row_index = [0,1]
col_index = [1,2]

s[row_index, col_index]

array([1, 7])

**Koşullu Eleman Seçme İşlemleri**

In [301]:
p = np.arange(10)
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [302]:
p <= 4 

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [306]:
p[p<=4]

array([0, 1, 2, 3, 4])

In [307]:
p[p>7]

array([8, 9])

In [308]:
p[p!=4]

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

# Pandas

# Seriler ile Analizler

# DataFrame'ler ile Analizler